kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: java
  namespace: openshift
spec:
  tags:
    - name: '11'
      from:
        kind: DockerImage
        name: 'registry.redhat.io/openjdk/openjdk-11-rhel8:latest'
