apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-template-service-broker
  namespace: {{ .Values.installServiceBrokerTargetNamespace }}
spec:
  targetNamespaces:
  - {{ .Values.installServiceBrokerTargetNamespace }}
