apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: codeready-workspaces
  namespace: {{ .Values.installTargetNamespace }}
spec:
  targetNamespaces:
  - {{ .Values.installTargetNamespace }}
