apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-template-service-broker
  namespace: {{ .Values.installServiceBrokerTargetNamespace }}
spec:
  channel: '4.4'
  installPlanApproval: Automatic
  name: openshifttemplateservicebroker
  source: redhat-operators
  sourceNamespace: openshift-marketplace

